name: My First GitHub Actions

on:
  push:
    branches:
      - main
      - testbranch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print message
        run: echo "Hello from GitHub Actions!"

      - name: List files
        run: ls -ll
