name: My First GitHub Actions

on:
  push:
    branches:
      - main
      - testbranch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Dcoker build
        run: docker build -t firstimage .

      - name: List files
        run: ls -la
